In [1]:
from astropy.io import fits
import numpy as np


In [10]:
hms2dec(23, 12, 6)

In [22]:
def hms2dec(hh,mm,ss):
    return (hh + mm/60 + ss/3600)*15
    
    

In [6]:
hms2dec(23, 12, 6)

348.025

In [11]:
def dms2dec(dg,arm,ars):
    value = abs(dg) + arm/60 + ars/3600
    if dg < 0:
        return -value
    else :
        return value


In [16]:
def angular_dist(ra1, dec1, ra2, dec2):
    # input and output and decimal degrees
    # Trig functions works in radians
    r1 = np.radians(ra1)
    r2 = np.radians(ra2)
    d1 = np.radians(dec1)
    d2 = np.radians(dec2)
    
    b = np.cos(d1)*np.cos(d2)*np.sin(np.abs(r1 - r2)/2)**2
    a = np.sin(np.abs(d1 - d2)/2)**2
    return np.degrees(2*np.arcsin(np.sqrt(a+b)))
    
    
    
    

In [27]:
fn='d:\\Users\\Anybody\\Documents\\ddastronomy\\bss.dat'
cat = np.loadtxt(fn, usecols=range(1, 7))

In [28]:
for objid,vect in enumerate(cat):
    print (vect)
    ra_dg = hms2dec(vect[0],vect[1],vect[2])
    dec_dg = dms2dec(vect[3],vect[4],vect[5])
    print (objid)
    print (ra_dg)
    print (dec_dg)


[  0.     4.    35.65 -47.    36.    19.1 ]
0
1.1485416666666666
-47.60530555555556
[  0.    10.    35.92 -30.    27.    48.3 ]
1
2.6496666666666666
-30.463416666666667
[  0.    11.     1.27 -26.    12.    33.1 ]
2
2.7552916666666665
-26.209194444444442


In [29]:
# Write your crossmatch function here.
import numpy as np
def hms2dec(hh,mm,ss):
    return (hh + mm/60 + ss/3600)*15
  
def dms2dec(dg,arm,ars):
    value = abs(dg) + arm/60 + ars/3600
    if dg < 0:
        return -value
    else :
        return value
  
  
def import_bss():
  cat = np.loadtxt('bss.dat', usecols=range(1, 7))
  tups = []
  for objid,vect in enumerate(cat):    
    ra_dg = hms2dec(vect[0],vect[1],vect[2])
    dec_dg = dms2dec(vect[3],vect[4],vect[5])
    tups.append((objid+1,ra_dg,dec_dg))
  return tups

def import_super():
  cat = np.loadtxt('super.csv', delimiter=',', skiprows=1, usecols=[0, 1])
  tups = []
  for objid,vect in enumerate(cat):    
    tups.append((objid+1,vect[0],vect[1]))
  return tups

def angular_dist(ra1, dec1, ra2, dec2):
    # input and output and decimal degrees
    # Trig functions works in radians
    r1 = np.radians(ra1)
    r2 = np.radians(ra2)
    d1 = np.radians(dec1)
    d2 = np.radians(dec2)
    
    b = np.cos(d1)*np.cos(d2)*np.sin(np.abs(r1 - r2)/2)**2
    a = np.sin(np.abs(d1 - d2)/2)**2
    return np.degrees(2*np.arcsin(np.sqrt(a+b)))

def find_closest(cat_tups, ra, dec):
  themin = np.inf
  myobj = None
  
  for tup in cat_tups:
    dist =  angular_dist(tup[1],tup[2], ra, dec)
    if dist < themin :
      themin = dist
      myobj = tup[0]
      
  return (myobj,themin)

def crossmatch(cat1_tups, cat2_tups, max_dist):
  matches = []
  no_matches = []
  for obj1,ra1,dec1 in cat1_tups:
    obj2, dist = find_closest(cat2_tups,ra1,dec1)
    if dist <= max_dist:
      matches.append((obj1,obj2,dist))
    else :
      no_matches.append(obj1)
  return matches,no_matches


  




# You can use this to test your function.
# Any code inside this `if` statement will be ignored by the automarker.
if __name__ == '__main__':
  bss_cat = import_bss()
  super_cat = import_super()

  # First example in the question
  max_dist = 40/3600
  matches, no_matches = crossmatch(bss_cat, super_cat, max_dist)
  print(matches[:3])
  print(no_matches[:3])
  print(len(no_matches))

  # Second example in the question
  max_dist = 5/3600
  matches, no_matches = crossmatch(bss_cat, super_cat, max_dist)
  print(matches[:3])
  print(no_matches[:3])
  print(len(no_matches))


OSError: bss.dat not found.

In [30]:
cat1 = np.array([[180, 30], [45, 10], [300, -45]])


In [31]:
cat1.shape

(3, 2)

In [27]:
 x = np.array([0, 1, 1, 3, 2, 1, 7, 23])

In [28]:
np.bincount(x)

array([1, 3, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1], dtype=int64)

In [69]:
values = [1, 5, 7, 7, 3, 6, 1, 1]
B = 4
#alues = [1, 1, 3, 2, 2, 6]
#=3
def median_bins(values,B):
    mean = np.mean(values)
    std = np.std(values)
    minval = mean-std
    maxval = mean+std
    binwith = 2*std/B
    bins = np.linspace(minval,maxval, num=B,endpoint=False)
    #print (bins)
    inds = np.digitize([v for v in values if v <maxval], bins)
    counts = np.bincount(inds)
    counts.resize(1,B+1)
    counts = counts.ravel()
    return mean,std,int(counts[0]),np.array(counts[1:].tolist())

  

In [71]:
median_bins([1, 1, 3, 2, 2, 6], 3)

(2.5, 1.707825127659933, 0, array([2, 3, 0]))

In [65]:
c.

SyntaxError: invalid syntax (<ipython-input-65-cf463a5954f9>, line 1)

In [46]:
mean,std,bin0,bincounts = median_bins([1, 1, 3, 2, 2, 6], 3)

In [48]:
bincounts

array([2], dtype=int64)

In [241]:
acc = bin0
N = len(values)
B = 3
binwith = 2*std/B
for ind, binc in enumerate(bincounts):
    if acc > (N+1)/2 :
        print (ind)
        print (acc)
        bstart  = (ind)*binwith
        bend  = (ind+1)*binwith       
        print ((bstart+bend)/2)
        break
    acc += binc


2
5
2.8463752127665547


In [200]:
np.resize(x,(1,4))

array([[1, 2, 3, 1]])

In [197]:
np.bincount(np.array([1,1,4]))

array([0, 2, 0, 0, 1], dtype=int64)

In [148]:
median_bins([1, 5, 7, 7, 3, 6, 1, 1], 4)

(3.875, 2.521780125229002, 3, array([3, 0, 1, 1, 1], dtype=int64))

In [97]:
import itertools
def median_approx(values, B):
    mean, std, bin0, bincounts = median_bins(values,B)
    binwith = 2*std/B
    minval = mean-std
    #print (binwith)
    N = len(values)
    total = 0
    #print ((N + 1)/2)
    for i,count_x in enumerate(itertools.chain([bin0],bincounts)):
        total += count_x
        #print (total)
        if total >= (N + 1)/2 :
            break
    start = minval+((i-1)*binwith) 
    end = minval+((i)*binwith)
    return ((start+end)/2)
            
        


In [98]:
median_approx([1, 5, 7, 7, 3, 6, 1, 1], 4)

4.50544503130725

In [99]:
 median_approx([1,1,3,2,2,6], 3)


2.5

In [80]:
median_bins([0, 1], 5)
#(0.5, 0.5, 0, array([ 1.,  0.,  0.,  0., 0.]))

(0.5, 0.5, 0, array([1, 0, 0, 0, 0]))

In [100]:
median_approx([0, 1], 5)


0.9

In [118]:
bins

array([0.79217487, 1.93072496, 3.06927504])

In [80]:
inds


array([0, 1, 1, 2, 2, 3, 3], dtype=int64)

In [2]:
import numpy as np
def angular_dist_input_rads(r1, d1, r2, d2):
    # input are in rads
    # output are in degrees
    # Trig functions works in radians    
    b = np.cos(d1)*np.cos(d2)*np.sin(np.abs(r1 - r2)/2)**2
    a = np.sin(np.abs(d1 - d2)/2)**2
    return np.degrees(2*np.arcsin(np.sqrt(a+b)))

In [3]:
# cats are degrees
cat1 = np.array([[180, 30], [45, 10], [300, -45]])
cat2 = np.array([[180, 32], [55, 10], [302, -44]])

In [4]:
cat1


array([[180,  30],
       [ 45,  10],
       [300, -45]])